var salario = 2000.50;
var aumento = 0.15;
var inflacao = 0.07;
var novoSalario = salario + (aumento*salario);
var novoSalarioInflacao = novoSalario -(inflacao*novoSalario);
console.log(novoSalario);
console.log(novoSalarioInflacao);
var strnovoSalario = `O novo salário é:\n R$\t\t ${novoSalario}`;
var strnovoSalarioInflacao = `O novo salário aplicada inflação é:\n R$ ${novoSalarioInflacao}`;
console.log(strnovoSalario);
console.log(strnovoSalarioInflacao);